version: "3"

services:
  spvd-nuxt:
    container_name: spvd-nuxt
    build:
      target: builder
      context: ./nuxt
      dockerfile: ./Dockerfile
    env_file:
      - ./nuxt/.env
    command: yarn dev --force
    networks:
      - strapi-net
      - traefik-gateway
    volumes:
      - ./nuxt:/nuxt

  strapi:
    container_name: spvd-strapi
    build:
      context: ./strapi
      dockerfile: ./Dockerfile
    env_file: ./strapi/.env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-gateway"
      - "traefik.http.routers.strapi-spvd.rule=Host(`strapi.spaargarenvandoorn.localhost`)"
      - "traefik.http.routers.strapi-spvd.entrypoints=http"
      - "traefik.http.routers.strapi-spvd.tls=false"
      - "traefik.http.services.strapi-spvd.loadbalancer.server.port=80"
    volumes:
      - ./strapi/config:/opt/app/config
      - ./strapi/src:/opt/app/src
      - ./strapi/package.json:/opt/package.json
      - ./strapi/yarn.lock:/opt/yarn.lock
      - ./strapi/.env:/opt/app/.env
      - ./strapi/public/uploads:/opt/app/public/uploads
    networks:
      - strapi-net
      - traefik-gateway
    depends_on:
      - db
    
  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - strapi-net
      - traefik-gateway

  nginx:
    image: nginx:1.15
    working_dir: /var/www/html
    depends_on:
      - spvd-nuxt
    networks:
      - default
      - traefik-gateway
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-gateway"
      - "traefik.http.routers.spvd-nuxt-nginx.rule=Host(`spaargarenvandoorn.localhost`)"
      - "traefik.http.routers.spvd-nuxt-nginx.entrypoints=http"
      - "traefik.http.routers.spvd-nuxt-nginx.tls=false"
      - "traefik.http.services.spvd-nuxt-nginx.loadbalancer.server.port=80"

    volumes:
      - ./nuxt/nginx/nginx.conf:/etc/nginx/nginx.conf

networks:
  traefik-gateway:
    name: traefik-gateway
    external: true
  strapi-net:
    name: strapi
volumes:
  db:
    driver: local
