# Use the official Node.js image from the Docker Hub, based on Alpine
FROM node:hydrogen-alpine

# Set the working directory in the container
WORKDIR /app

COPY . .

# Start the Node.js application
CMD ["echo", "yea buddy"]
